apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-api
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-api
  template:
    metadata:
      labels:
        app: event-api
    spec:
      containers:
      - name: api
        image: event-api:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        # Inject ALL keys from ConfigMap and Secret as environment variables
        envFrom:
        - configMapRef:
            name: api-config
        - secretRef:
            name: api-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
