apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce  # RWO = single node read/write
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Default storage class
